<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.28"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
        <PackageReference Include="QuestPDF" Version="2026.6.0" />
        <PackageReference Include="SkiaSharp" Version="4.148.0" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.148.0" />
        <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.148.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <Content Remove="data\full_game.json" />
      <None Include="data\full_game.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Content Remove="data\jinx.json" />
      <None Include="data\jinx.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Content Remove="data\night_order.json" />
      <None Include="data\night_order.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\_dawn.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\_demon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\_demons.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\_dusk.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\_minion.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\_minions.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\_outsiders.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\_page2.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\_townsfolk.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\config.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="fonts\Arlekino.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="fonts\Candara.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="fonts\Georgia.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="fonts\Georgia-Italic.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="fonts\Royal_Times_New_Roman.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Content Remove="outputs\Trust Is Just A Word - Güven Sadece Bir Kelimedir.json" />
      <None Include="outputs\Trust Is Just A Word - Güven Sadece Bir Kelimedir.json">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
